version: '3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.1
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  broker:
    image: confluentinc/cp-kafka:7.0.1
    container_name: broker
    depends_on:
      - zookeeper
    ports:
      - "29092:29092"
      - "9092:9092"
      - "9101:9101"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_JMX_PORT: 9101
      KAFKA_JMX_HOSTNAME: localhost

  elasticsearch01:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.14.3
    container_name: elasticsearch01
    environment:
      - cluster.name=elasticsearch-cluster
      - node.name=es01
      - discovery.seed_hosts=elasticsearch02,elasticsearch03
      - cluster.initial_master_nodes=es01,es02,es03
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
      - "9300:9300"

  elasticsearch02:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.14.3
    container_name: elasticsearch02
    environment:
      - cluster.name=elasticsearch-cluster
      - node.name=es02
      - discovery.seed_hosts=elasticsearch01,elasticsearch03
      - cluster.initial_master_nodes=es01,es02,es03
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9201:9200"
      - "9301:9300"

  elasticsearch03:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.14.3
    container_name: elasticsearch03
    environment:
      - cluster.name=elasticsearch-cluster
      - node.name=es03
      - discovery.seed_hosts=elasticsearch01,elasticsearch02
      - cluster.initial_master_nodes=es01,es02,es03
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9202:9200"
      - "9302:9300"

  kibana:
    image: docker.elastic.co/kibana/kibana:8.14.3
    container_name: kibana
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch01:9200
    depends_on:
      - elasticsearch01
      - elasticsearch02
      - elasticsearch03

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_PASSWORD: 'admin'
    volumes:
      - grafana-data:/var/lib/grafana

volumes:
  grafana-data:


# version: '3'
# services:
#   zookeeper:
#     image: confluentinc/cp-zookeeper:7.0.1
#     container_name: zookeeper
#     ports:
#       - "2181:2181"
#     environment:
#       ZOOKEEPER_CLIENT_PORT: 2181
#       ZOOKEEPER_TICK_TIME: 2000

#   broker:
#     image: confluentinc/cp-kafka:7.0.1
#     container_name: broker
#     depends_on:
#       - zookeeper
#     ports:
#       - "29092:29092"
#       - "9092:9092"
#       - "9101:9101"
#     environment:
#       KAFKA_BROKER_ID: 1
#       KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
#       KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
#       KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:29092,PLAINTEXT_HOST://localhost:9092
#       KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
#       KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
#       KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
#       KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
#       KAFKA_JMX_PORT: 9101
#       KAFKA_JMX_HOSTNAME: localhost

#   elasticsearch01:
#     image: docker.elastic.co/elasticsearch/elasticsearch:8.14.3
#     container_name: elasticsearch01
#     environment:
#       - cluster.name=elasticsearch-cluster
#       - node.name=es01
#       - discovery.seed_hosts=elasticsearch02,elasticsearch03
#       - cluster.initial_master_nodes=es01,es02,es03
#       - xpack.security.enabled=false
#       - ES_JAVA_OPTS=-Xms512m -Xmx512m
#     ports:
#       - "9200:9200"
#       - "9300:9300"

#   elasticsearch02:
#     image: docker.elastic.co/elasticsearch/elasticsearch:8.14.3
#     container_name: elasticsearch02
#     environment:
#       - cluster.name=elasticsearch-cluster
#       - node.name=es02
#       - discovery.seed_hosts=elasticsearch01,elasticsearch03
#       - cluster.initial_master_nodes=es01,es02,es03
#       - xpack.security.enabled=false
#       - ES_JAVA_OPTS=-Xms512m -Xmx512m
#     ports:
#       - "9201:9200"
#       - "9301:9300"

#   elasticsearch03:
#     image: docker.elastic.co/elasticsearch/elasticsearch:8.14.3
#     container_name: elasticsearch03
#     environment:
#       - cluster.name=elasticsearch-cluster
#       - node.name=es03
#       - discovery.seed_hosts=elasticsearch01,elasticsearch02
#       - cluster.initial_master_nodes=es01,es02,es03
#       - xpack.security.enabled=false
#       - ES_JAVA_OPTS=-Xms512m -Xmx512m
#     ports:
#       - "9202:9200"
#       - "9302:9300"

#   init_elasticsearch:
#     image: curlimages/curl:latest
#     depends_on:
#       - elasticsearch01
#       - elasticsearch02
#       - elasticsearch03
#     entrypoint: ["/bin/sh", "/scripts/init-elasticsearch.sh"]
#     volumes:
#       - ./init-elasticsearch.sh:/scripts/init-elasticsearch.sh
